### ISSUE TITLE
Issue_01 (Make Cards For Lesson)

### ISSUE THREAD

**Issue by vipuldcoder** [UdacityAndroidBasicsScholarship/scholar-quiz#3]
In this Issue, There is a first screen layout after login. In this, we make cards For all lesson.

**Comment by mohancm** [comment]
yes, that would be great

**Comment by amCap1712** [comment]
What color scheme or theme should be used? What all information should be provided with each card?

**Comment by prafulnayak** [comment]
check and close mohan
