### ISSUE TITLE
Kindly follow class member naming convention.

### ISSUE THREAD

**Issue by OjasviBhargava** [UdacityAndroidBasicsScholarship/scholar-quiz#37]
https://github.com/UdacityAndroidBasicsScholarship/scholar-quiz/blob/e3c92ed5954cd202635b476cc3c4bae1365ef372/app/src/main/java/org/sairaa/scholarquiz/AppInfo.java#L17

**Comment by OjasviBhargava** [comment]
You can change `public static FirebaseAuth firebaseAuth; ` to  `public static FirebaseAuth mFirebaseAuth;`

**Comment by mohancm** [comment]
Alright @OjasviBhargava . Thanks for Informing 👍
