### ISSUE TITLE
Issue_02 (Make another Layout For Lesson_02)

### ISSUE THREAD

**Issue by vipuldcoder** [UdacityAndroidBasicsScholarship/scholar-quiz#4]
In this issue, we make Button layout For lesson_02. When the user clicks on The Lesson_02 Quiz will show where MCQ(Multiple Choice Questions) for Lesson_02 which we have learned.

**Comment by prafulnayak** [comment]
When a user clicks on Any Lesson, the Quiz Screen will open and it will have all the Quizzes under that lesson. When the user clicks on Quiz, the MCQ screen will open.
