### ISSUE TITLE
Decide the color theme and distribute task 

### ISSUE THREAD

**Issue by mantyshah** [UdacityAndroidBasicsScholarship/scholar-quiz#9]
Hi, Guys can we decide the color theme of the application. Also I suggest the mods to distribute task make a to-do list for the task.

**Comment by mohancm** [comment]
yes, We are working on UI for now
once after decided, will push the code.
you can start contributing according to that

**Comment by mantyshah** [comment]
Can I contribute to the UI part as well?

**Comment by mohancm** [comment]
yes, once we push our UI part, you can start adding your ideas
will check and decide with the team. :)

**Comment by mantyshah** [comment]
Thanks then I am not doing any changes to XML code.

**Comment by prafulnayak** [comment]
If the issue solved, Close it
